### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ExalDraen** [unixunion/python-libsolace#15]
Hi,

Just raising this issue to check what the status of this project is - I see it hasn't been touched for ~3 years so are you intending to do any more work on it?

If not, do you have any objections to me forking and publishing this to PyPI (maintaining the copyright notices as per the license)?

Cheers.

**Comment by unixunion** [comment]
@ExalDraen sorry for delayed response. Yes the project has not made any progress in a while, it might be a few bug patches behind, but no features are being added. I am looking to deprecate this, and release a SEMPv2 version instead. SEMPv2 is now a better option than all the SEMPv1 XML document handling. 

We have a working SEMPv2 implementation which is now "stable" which I will do the necessary to get made public.

**Comment by ExalDraen** [comment]
Agree that SEMPv2 is better, we just have a use case that isnt't covered by v2 yet (stats extraction) so we have to use v1; thus the desire to use `libsolace`.
Not planning to add many features, it was mainly to be able to add pypi packaging and a bit of tidyup. I assume you're ok with me doing that ina  fork (https://github.com/ExalDraen/python-libsolace)? 

Meantime, looking forward to your SEMPv2 implentation!

**Comment by unixunion** [comment]
SEMPv2 needs a few more releases before it can completely replace v1. Lets hope its soon! 
Fork and go nuts! :D Ill come leave you a note when Im done with a v2 impl.

**Comment by ExalDraen** [comment]
Thanks :bowing_man: . I'll close out this issue then.
