### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jtyr** [unixunion/python-libsolace#2]
Please could you specify under which license this package is available and add a LICENSE file? If you are unsure which license to choose, I would sugest MIT license (https://en.wikipedia.org/wiki/MIT_License).

**Comment by unixunion** [comment]
Yeah MIT is good. ill add headers and a license file shortly.

/K

**Comment by jtyr** [comment]
It's not necessary to add license header into every file. Standalone `LICENSE` file will do it.

**Comment by jtyr** [comment]
LICENSE file added. Please could you tag the repo and make a new release?
